### ISSUE TITLE
Translations on M1 crash docker container 

### ISSUE THREAD

**Issue by caudurodev** [LibreTranslate/LibreTranslate#524] opened 2023-10-27 14:38 UTC
I have pulled the latest docker images:

- libretranslate/libretranslate:latest
- libretranslate/libretranslate:v1.4
- libretranslate/libretranslate:v1.3.13

All have an issue which cause an internal error when attempting any translation that is not en->en. The issue occurs both on the web interface and via the API. There is no relevant logging info even when `LT_DEBUG=1` flag is enabled.

Downloading currently `LT_LOAD_ONLY=en,de` models and can verify the files are present in 
```
/home/libretranslate/.local/share/argos-translate/packages/
```

Accessing the url `http://localhost:5000/?source=de&target=en&q=H`

results in:
```
libretranslate exited with code 139
libretranslate  | Updating language models
libretranslate  | Found 86 models
libretranslate  | Keep 2 models
libretranslate  | Loaded support for 2 languages (2 models total)!
libretranslate  |  * Serving Flask app 'libretranslate.app'
libretranslate  |  * Debug mode: off
libretranslate  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
libretranslate  |  * Running on all addresses (0.0.0.0)
libretranslate  |  * Running on http://127.0.0.1:5000
libretranslate  |  * Running on http://172.28.0.2:5000
libretranslate  | Press CTRL+C to quit
```

![image](https://github.com/LibreTranslate/LibreTranslate/assets/60057887/e9a910ff-4638-45db-a2db-b206e39a7cf9)

I'm using docker-compose.yml:
```
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    ports:
    - "5000:5000"
    restart: unless-stopped
    environment:
      - LT_UPDATE_MODELS=1
      - LT_DEBUG=1
      - LT_LOAD_ONLY=en,de
```

My env:

Mac M2, using docker desktop 4.24.2 (124339) (Docker engine  24.0.6)

**Comment by pierotofy** [comment] 2023-10-27 16:30
Might be some issue with ctranslate2/stanza on ARM.

**Comment by caudurodev** [comment] 2023-10-28 10:46
I can confirm that the same images work in linux

**Comment by sunjam** [comment] 2023-10-28 15:27
> Might be some issue with ctranslate2/stanza on ARM.

Tried this docker-compose on arm64 on Linux and seeing same error.
`Cannot Load /Translate`

**Comment by sunjam** [comment] 2023-10-28 15:34
I just tried switching to the older `image: libretranslate/libretranslate:v1.3.12`
and now the  docker-compose file works @caudurodev

**Comment by beshambher** [comment] 2023-10-28 22:44
Latest version crashes for me too on Mac M1. Normal code run locally works though, I'm using

> python3 main.py --port 6060 --load-only en,es,de,fr --update-models --debug

One more thing, the html translation doesn't work locally. I see the beta tag on it but not sure what that means because its working on https://libretranslate.com/ but not on localhost on latest code. Idk if I should open a new issue for this.

**Comment by CodeStarrk** [comment] 2023-10-29 21:00
I am also on a mac m1 chip, but when moving to the older image I now get this error when i try to translate:

`Cannot translate text: Unsupported model binary version. This executable supports models with binary version v5 or below, but the model has binary version v6. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)`

**Comment by CodeStarrk** [comment] 2023-10-29 21:43
Certain languages work and some don't (noticed it with Dutch to English) is it possible to edit the language model version it downloads to downgrade the language versions?

**Comment by pierotofy** [comment] 2023-10-30 00:40
This seems to be related to docker, as a native M1 installation (via pip) is able to use all models without issues on ARM.

**Comment by pierotofy** [comment] 2023-10-30 01:09
Running with podman returns a different error message: `could not create a primitive descriptor for a matmul primitive`

This is not a string in ctranslate2, which suggests a deeper issue in one of ctranslate2's dependencies.

**Comment by pierotofy** [comment] 2023-10-30 01:36
Downgrading pytorch to 2.0.1 fixes the issue; it looks like a regression introduced in torch 2.1.0.

**Closed** 2023-10-30 01:46 UTC
Labels: bug
