### ISSUE TITLE
Mistranslated japanese

### ISSUE THREAD

**Issue by Thewisem** [LibreTranslate/LibreTranslate#91] opened 2021-05-24 14:15 UTC
Hello in japanese is konichiwa not お問い合わせ.. That means contact us not hello

**Comment by pierotofy** [comment] 2021-05-24 14:19
Duplicate of #81

**Comment by PJ-Finlay** [comment] 2021-05-24 22:04
https://github.com/argosopentech/argos-translate/issues/119

**Closed** 2022-01-31 11:11 UTC
Labels: duplicate
