### ISSUE TITLE
'NoneType' object has no attribute 'translate'

### ISSUE THREAD

**Issue by a0m0rajab** [LibreTranslate/LibreTranslate#301] opened 2022-08-21 13:45 UTC
Hey, I just noticed a bug in the translation to different langaues if I used one word: 
![image](https://user-images.githubusercontent.com/18273833/185793911-058ac60f-caaa-4ae8-b592-fd16e0d7e23f.png)

**Comment by a0m0rajab** [comment] 2022-08-21 13:47
Translation to Arabic are broken as well:
https://libretranslate.com/?source=en&target=ar&q=How%2520yt

![image](https://user-images.githubusercontent.com/18273833/185793985-a604e529-8c1d-4b06-978c-3a5dcd8401d8.png)


I was just playing around to see the results.

**Comment by rio-codes** [comment] 2022-08-21 21:54
I'm not sure if the repetition bug and the  `Cannot translate text: 'NoneType' object has no attribute 'translate'` error are related (I definitely got both when playing around with Hebrew, but can't remember the order I tried things in or what prompted them). It also only occurs on the website for me, a local instance works correctly. I'm still trying to figure out which object the error is referring to, I'll continue to dig into it. Since this is only happening on the web (v 1.2.9) and not locally for me, maybe it got fixed in one of the commits since the last release?

More info: 
- I have tried it in Firefox 103.0.2 and Chromium 104.0.5112.101, both reproduce the bug on the web but not locally.
- I haven't been able to reproduce it from Hebrew back to English on the web nor locally; I don't have an Arabic keyboard installed so I haven't tested direct input, but copy-pasting the results from the local install back to the web (كيف) worked fine too.
- Both Hebrew and Arabic read right-to-left rather than left-to-right but the initial bug @a0m0rajab posted was in Turkish (Left-to-right). To me, this indicates that they are 2 different bugs. I also get the repetition bug from English to Turkish (Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl Nasıl) and also in Hebrew:

![image](https://user-images.githubusercontent.com/791713/185812256-18fe7f64-310c-48a5-94f7-f73ce517e963.png)

 both on the web and locally. However, the only other solely right-to-left language available is Persian, and that seems to work fine. (Chinese, Japanese, and Korean apparently have some right-to-left dialects but the default for those 3 seems to be left-to-right.) Maybe this should be broken out into 2 different bugs? (Repetition of single words and ` 'NoneType' object has no attribute 'translate'` error in right-to-left languages?)
 - I also found #183 which implies that the repetition bug is a training problem with the neural net, but that issue is pretty old and slightly different. (In that issue it didn't translate properly at all, here it seems like it gets the right word but repeats it)

**Comment by rio-codes** [comment] 2022-08-21 22:08
I just noticed that the `NoneType` bug has another issue open: #295. There it was reproduced in Norwegian and Danish (left-to-right) so maybe I am off-track with that idea.

**Comment by rio-codes** [comment] 2022-08-22 18:29
I noticed one more thing:
![image](https://user-images.githubusercontent.com/791713/185992435-19a21226-c89a-4453-9915-8855d2faa46f.png)
I am wondering if it is trying to translate different tenses/forms of the word? Like in this case it is showing the present progressive (helping) and the root word (help)? When it has a whole sentence, it "knows" what the tense is, but the word by itself has different possible meanings without context? A fix might be to either specify the different forms or just drop repetition of single words if they are exactly the same. In this case it does help.

**Comment by a0m0rajab** [comment] 2022-08-22 18:51
Yeah, this is a bit tricky, I have not fully checked the system but it caught my interest, I may dig in it when I got have a bit of time.

**Comment by PJ-Finlay** [comment] 2022-08-26 11:39
Like posted above the repetition bug is separate. In that case the neural net sometimes can get stuck in a loop.

For the ` 'NoneType' object has no attribute 'translate'` issue what may be happening is some error is making the `argostranslate.translate.ITranslation` None so it fails when the `translate` function is called.

https://argos-translate.readthedocs.io/en/latest/source/argostranslate.html#argostranslate.translate.ITranslation

**Comment by PJ-Finlay** [comment] 2022-08-26 12:09
Closing as 

https://github.com/LibreTranslate/LibreTranslate/issues/295#issuecomment-1228410299

**Closed by PJ-Finlay** 2022-08-26 12:09 UTC
Labels: bug, good first issue, help wanted
