### ISSUE TITLE
Cannot translate text: 'NoneType' object has no attribute 'translate'

### ISSUE THREAD

**Issue by SethFalco** [LibreTranslate/LibreTranslate#295] opened 2022-08-07 10:17 UTC
On the website ([libretranslate.com](https://libretranslate.com/?source=auto&target=en)) I ran into this error when trying to translate Norwegian text with **Auto Detect (Experimental)** enabled.

It results in a 500 (internal server error) with the following message:

> Cannot translate text: 'NoneType' object has no attribute 'translate'

~~I'm going to assume that the error stems from the auto-detection picking out a language which LibreTranslate doesn't support, but have not verified if this is the case yet. (Just a hypothesis.)~~

I realize now that LibreTranslate doesn't support Norwegian, but this should still probably be handled better regardless.

**Comment by salihbenlalla** [comment] 2022-08-12 19:41
i'm facing the same error !

**Comment by JuanPabloAmador** [comment] 2022-08-14 15:31
I have the same error, but in my case it is trying to use the docker image. 
To reproduce it you just have to lift the docker image go to localhost:5000 the front-end itself fails, it can also be played by using a rest like postman client to the endpoint localhost:5000/translate

**Comment by pierotofy** [comment] 2022-08-14 16:05
Can you share the exact text input you're using?

**Comment by JuanPabloAmador** [comment] 2022-08-15 12:30
> Can you share the exact text input you're using?

Any text, when writing the front-end sends the request to the /translate endpoint and breaks. 

the steps were: 

1º `docker run -ti --rm -p 5000:5000 libretranslate/libretranslate`
2º Open localhost:5000
3º Write anything in the text-box. 

Thanks for your time.

**Comment by SethFalco** [comment] 2022-08-15 12:44
I experimented with it a little since I didn't want to share the original text I actually received.

I can reproduce it on prod with the following:
https://libretranslate.com/?source=auto&target=en&q=samtale

Source: auto
Target: en
Input: samtale

**Comment by dingedi** [comment] 2022-08-15 14:40
I just checked and models exist for EN -> DA and DA-> EN
[https://www.argosopentech.com/argospm/index/](https://www.argosopentech.com/argospm/index/)

**Comment by dingedi** [comment] 2022-08-15 14:54
It's strange because it works on libretranslate.de


[https://libretranslate.de/?source=auto&target=en&q=samtale](https://libretranslate.de/?source=auto&target=en&q=samtale)

**Comment by pierotofy** [comment] 2022-08-15 19:21
Mm, good point; I was able to manually download the language model and extract it in `~/.local/share/argos-translate/packages` and that solved the problem.

Perhaps an issue with the `install_models.py` script then.

**Comment by PJ-Finlay** [comment] 2022-08-26 11:53
I think this is probably an issue with a specific model failing to download. So for example, if the English to Danish model fails to download then we get this error when trying to translate English to Danish.

**Comment by PJ-Finlay** [comment] 2022-08-26 12:08
I'm not sure what the best fix for this is. We already have [redundancy with multiple download links and retries](https://community.libretranslate.com/t/improving-package-download/213/4?u=argosopentech); I'm also currently working on improvements to the models CDN so hopefully this happens less frequently in the future.

We should probably handle this function call in LibreTranslate failing more gracefully too:
https://github.com/LibreTranslate/LibreTranslate/blob/6cc4f94da2a55f5ead9b588bf43ab97c9e355b31/app/app.py#L520

**Comment by PJ-Finlay** [comment] 2022-08-27 13:19
I just set up a better server for cdn.argosopentech.io so hopefully this issue won't occur as frequently going forward.

**Comment by pierotofy** [comment] 2022-09-02 16:46
I finally figured this out: there were some old files in `~/.local/cache/argos-translate/downloads/` that seemed to interfere with the `install_models.py` script, so a few languages (Danish -> English included) were missed.

Nuking the `~/.local/cache/argos-translate` folder and re-running `install_models.py`  fixed it.

**Closed by pierotofy** 2022-09-02 16:46 UTC
Labels: bug, good first issue, help wanted

**Comment by vossilius** [comment] 2022-09-07 12:21
Same problem here using [latest](https://hub.docker.com/layers/libretranslate/libretranslate/latest/images/sha256-318c24ca411732903393350c06dd75cde695c9986edbd6df938ad53d7e6f95b3?context=explore) Docker container

**Comment by Christopher-Hayes** [comment] 2022-12-04 12:25
Ran into this issue as well. I'm not sure the significance of `~/.local/cache/argos-translate/downloads/`, but if it's empty, doesn't seem to make a difference. The main location for language models seems to be `/root/.local/share/argos-translate/packages/`. So, what languages show in the GUI, will depend on that folder alone.

Also, note that the models seem to be loaded into memory or a temporary location, so if you remove a model folder from that location and restart LibreTranslate, it'll keep showing the language model and continue to work, only after restarting the server itself did the model finally disappear from the GUI.

In my case, I was manually moving models into the packages folder due to storage limits on my EC2 instance. I initially put select English -> Other Language models on it since that was all I needed, later I wanted to also translate the other languages back to English. LibreTranslate seems to assume you have models going in both directions. So if you have a Chinese -> English model in the `/packages` folder, LibreTranslate will let you also translate English -> Chinese in the GUI, despite that model not being present. Which then leads to the error above when it tries to use a model that doesn't exist.

**Unrelated:** My understanding is `/downloads` are just the zipped models that were downloaded, but once unzipped into the `/packages`, are no longer used. It'd probably be a good idea to eagerly delete these zip files. The models are already quite large, so having a dozen or so 100MB files that aren't needed become problematic on a space-constrained server.

**Comment by PJ-Finlay** [comment] 2022-12-04 14:46
Argos Translate downloads argosmodel packages to `$HOME/.local/cache/argos-translate/` then unzips them to `$HOME/.local/share/argos-translate/packages/`.

I think you should be able to delete the unzipped models from the cache directory after they've been installed if you want to save space.
