### ISSUE TITLE
Chinese being installed when Dutch, English requested

### ISSUE THREAD

**Issue by irfanHaslanded** [LibreTranslate/LibreTranslate#267] opened 2022-05-30 00:05 UTC
libretranslate --debug --load-only 'en,nl'
Updating language models
Found 58 models
Keep 2 models
Downloading Dutch → English (1.4) ...
Downloading English → Dutch (1.4) ...
Loaded support for 3 languages (2 models total)!
Installing transliteration models for the following languages: zh, nl
[polyglot_data] Downloading package transliteration2.zh to /home/irfan
[polyglot_data]     /.local/share/LibreTranslate/polyglot_data...
[polyglot_data] Downloading package transliteration2.nl to /home/irfan
[polyglot_data]     /.local/share/LibreTranslate/polyglot_data...
 * Serving Flask app 'app.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)

**Comment by andersmmg** [comment] 2022-06-24 05:15
Where are you seeing that it's loading Chinese? I don't see that anywhere.

**Comment by dingedi** [comment] 2022-06-24 05:39
Ah this line, zh is chinese

 ```
Installing transliteration models for the following languages: zh, nl
```

**Comment by andersmmg** [comment] 2022-06-24 06:57
Ah, I was expecting cn, which I believe is Mandarin maybe? I was not able to reproduce this.
```
$ libretranslate --debug --load-only 'en,nl'

Updating language models
Found 58 models
Keep 2 models
Downloading Dutch → English (1.4) ...
Downloading English → Dutch (1.4) ...
Loaded support for 2 languages (2 models total)!
Installing transliteration models for the following languages: nl
[polyglot_data] Downloading package transliteration2.nl to /home/ander
[polyglot_data]     smmg/.local/share/LibreTranslate/polyglot_data...
 * Serving Flask app 'app.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
```

**Comment by VagabondAzulien** [comment] 2022-07-03 04:32
I am able to replicate this. Using the following `docker-compose.yml`:

```
version: "3"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - 127.0.0.1:27272:5000
    command: --req-limit 100 --char-limit 500 --load-only "en,nl"
```

Checking available languages via the API:

```
$ curl -X GET "https://translate.exp.farm/languages"
[{"code":"en","name":"English"},{"code":"zh","name":"Chinese"},{"code":"nl","name":"Dutch"}]
```

**Comment by VagabondAzulien** [comment] 2022-07-09 16:08
Looks to be because of the models in Argos-Translate:

Here: https://raw.githubusercontent.com/argosopentech/argospm-index/main/index.json

The Dutch payload includes a Chinese link:

```
    {
        "package_version": "1.4",
        "argos_version": "1.4",
        "from_code": "nl",
        "from_name": "Dutch",
        "to_code": "en",
        "to_name": "English",
        "links": [
            "https://argosopentech.nyc3.digitaloceanspaces.com/argospm/translate-nl_en-1_4.argosmodel",
            "https://cdn.argosopentech.io/translate-zh_en-1_1.argosmodel",
            "ipfs://Qmd343XFXGJDpsWQ2G1s4v1hjbzJwUHnm8y3qEVNht6FSk"
        ]
    },
```

**Comment by PJ-Finlay** [comment] 2022-07-15 13:09
This is fixed now, it was a typo in the package index.

**Closed by PJ-Finlay** 2022-07-15 13:09 UTC
Labels: help wanted, possible bug
